# Generated by Django 4.2.2 on 2023-06-12 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.TextField()),
                ('reference', models.TextField(null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DOEvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField()),
                ('unit', models.CharField(max_length=100)),
                ('doe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doe')),
            ],
        ),
        migrations.CreateModel(
            name='Var',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Varlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('value_num', models.FloatField(default=0.0, null=True)),
                ('doe_var_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doevar')),
            ],
        ),
        migrations.AddField(
            model_name='doevar',
            name='var_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.var'),
        ),
        migrations.CreateModel(
            name='DOErun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.varlevel')),
            ],
        ),
    ]
